### ISSUE TITLE
Checking the Results

### ISSUE THREAD

**Issue by BsNoSi** [schulle4u/yellow-plugin-socialtags#2]
Something possibly irritating:

- Some Twitter-Tools (eg TweetDeck) do not show the card in own tweets. 
- The cards are created after tweet is sent, existing links (without cards) are not updated.

To see the presentation without sending a tweet you can use the [Twitter Card Validator](https://cards-dev.twitter.com/validator) to see the result.

**Comment by schulle4u** [comment]
Yes, i can confirm this, old Tweets are not updated. Only if you repost an old article link to your website, the Twitter card displays as expected. So I think this is rather a general Twitter issue. 
Can't say much about TweetDeck because this site is not very friendly to screen-reader users like me.
